/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Edna Ordoñez
 */
public class Acciones extends javax.swing.JPanel {

    /**
     * Creates new form Crear
     */
    public Acciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPatrullar = new javax.swing.JButton();
        jReportarEstado = new javax.swing.JButton();
        jMostrarMision = new javax.swing.JButton();
        jSaludar = new javax.swing.JButton();
        jRegañar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ACCIONES SOBRE SOLDADOS");

        jPatrullar.setBackground(new java.awt.Color(255, 204, 255));
        jPatrullar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPatrullar.setText("Patrullar");
        jPatrullar.setBorder(new javax.swing.border.MatteBorder(null));
        jPatrullar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPatrullar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatrullarActionPerformed(evt);
            }
        });

        jReportarEstado.setBackground(new java.awt.Color(255, 204, 255));
        jReportarEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jReportarEstado.setText("Reportar estado");
        jReportarEstado.setBorder(new javax.swing.border.MatteBorder(null));
        jReportarEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jReportarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReportarEstadoActionPerformed(evt);
            }
        });

        jMostrarMision.setBackground(new java.awt.Color(255, 204, 255));
        jMostrarMision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMostrarMision.setText("Mostrar misión");
        jMostrarMision.setBorder(new javax.swing.border.MatteBorder(null));
        jMostrarMision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMostrarMision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMostrarMisionActionPerformed(evt);
            }
        });

        jSaludar.setBackground(new java.awt.Color(255, 204, 255));
        jSaludar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSaludar.setText("Saludar");
        jSaludar.setBorder(new javax.swing.border.MatteBorder(null));
        jSaludar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaludarActionPerformed(evt);
            }
        });

        jRegañar.setBackground(new java.awt.Color(102, 0, 0));
        jRegañar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRegañar.setForeground(new java.awt.Color(255, 255, 255));
        jRegañar.setText("Regañar");
        jRegañar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRegañar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegañarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jSaludar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jRegañar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPatrullar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jReportarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jMostrarMision, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReportarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMostrarMision, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegañar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSaludar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPatrullar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jPatrullarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        JOptionPane.showMessageDialog(null, "Patrullando...");
    }                                          

    private void jReportarEstadoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        JOptionPane.showMessageDialog(null, "Reportando estado...");
    }                                               

    private void jMostrarMisionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        JOptionPane.showMessageDialog(null, "Mostrando misión...");
    }                                              

    private void jSaludarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JOptionPane.showMessageDialog(null, "Saludando...");
    }                                        

    private void jRegañarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JOptionPane.showMessageDialog(null, "Regañando...");
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMostrarMision;
    private javax.swing.JButton jPatrullar;
    private javax.swing.JButton jRegañar;
    private javax.swing.JButton jReportarEstado;
    private javax.swing.JButton jSaludar;
    // End of variables declaration                   
}
